project:
  type: website
  output-dir: docs

website:
  title: "quartoCourseBlog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/nmcclinton30/rcc_nyla_mcclinton
      - icon: twitter
        href: https://twitter.com/MattCrumpLab
format:
  html:
    theme: sketchy
    css: styles.css

editor: visual

